language: python
python:
  - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "3.7-dev"
sudo: false
# command to install dependencies
install:
  - pip install wheel
  - pip install --upgrade pip setuptools
  - pip --version
  - pip install tox-travis
  - pip install tox
# command to run tests
script:
  - "tox"
#after_success:
#  coveralls
